import { Targets } from "cppbuild";

var files = [
	"CPPBuild.js",
	"Precomp.cpp",
	"Precomp.h",
	"Text/StringFormat.cpp",
	"Text/StringFormat.h",
	"Text/Text.cpp",
	"Text/Text.h",
	"Text/UTF16.cpp",
	"Text/UTF16.h",
	"Text/UTF8Reader.cpp",
	"Text/UTF8Reader.h",
	"Json/JsonValue.cpp",
	"Json/JsonValue.h",
	"IOData/DataBuffer.cpp",
	"IOData/DataBuffer.h",
	"IOData/Directory.cpp",
	"IOData/Directory.h",
	"IOData/File.cpp",
	"IOData/File.h",
	"IOData/FilePath.cpp",
	"IOData/FilePath.h",
	"IOData/IODevice.h",
	"IOData/MemoryDevice.cpp",
	"IOData/MemoryDevice.h",
	"Zip/miniz.c",
	"Zip/miniz.h",
	"Zip/ZipReader.cpp",
	"Zip/ZipReader.h",
	"Zip/ZipWriter.cpp",
	"Zip/ZipWriter.h",
	"Logger/Logger.cpp",
	"Logger/Logger.h",
	"Webserver/ActionModule.cpp",
	"Webserver/ActionModule.h",
	"Webserver/FileModule.cpp",
	"Webserver/FileModule.h",
	"Webserver/WebContext.cpp",
	"Webserver/WebContext.h",
	"Webserver/WebController.cpp",
	"Webserver/WebController.h",
	"Webserver/WebHeaderName.cpp",
	"Webserver/WebHeaderName.h",
	"Webserver/WebModule.h",
	"Webserver/WebRequest.cpp",
	"Webserver/WebRequest.h",
	"Webserver/WebRequestUrl.cpp",
	"Webserver/WebRequestUrl.h",
	"Webserver/WebRequestVerb.h",
	"Webserver/WebResponse.cpp",
	"Webserver/WebResponse.h",
	"Webserver/Webserver.cpp",
	"Webserver/Webserver.h",
	"Webserver/Socket/BufferedSocket.cpp",
	"Webserver/Socket/BufferedSocket.h",
	"Webserver/Socket/SocketHandle.cpp",
	"Webserver/Socket/SocketHandle.h",
	"Webserver/Socket/SocketWebserver.cpp",
	"Webserver/Socket/SocketWebserver.h",
	"Webserver/HttpSys/HttpSysIoContext.h",
	"Webserver/HttpSys/HttpSysReceiveRequest.cpp",
	"Webserver/HttpSys/HttpSysReceiveRequest.h",
	"Webserver/HttpSys/HttpSysSendResponse.cpp",
	"Webserver/HttpSys/HttpSysSendResponse.h",
	"Webserver/HttpSys/HttpSysWebserver.cpp",
	"Webserver/HttpSys/HttpSysWebserver.h",
];

var webserver = Targets.addStaticLibrary("Common");
webserver.addFiles(files);
webserver.addIncludePaths([".", ".."]);
webserver.addDefines(["WIN32", "_WIN32", "UNICODE", "_UNICODE"]);
